# Nama workflow yang akan muncul di tab Actions GitHub
name: Run Telegram Bot

# Pemicu (trigger) untuk menjalankan workflow ini
on:
  # 1. Jalankan saat ada push ke branch 'main'
  push:
    branches: [ "main" ]
    
  # 2. Izinkan untuk menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

jobs:
  run-bot:
    # Jalankan di lingkungan Ubuntu terbaru
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode dari repositori
      # Ini akan mengunduh kode Anda ke runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup lingkungan Python
      # Menentukan versi Python yang akan digunakan
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Anda bisa ganti ke 3.9, 3.11, dll.

            # Langkah 3: Install semua library yang dibutuhkan
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # !!! LANGKAH DIAGNOSTIK BARU - TAMBAHKAN INI !!!
      - name: Check installed packages version
        run: |
          echo "--- Checking httpx version ---"
          pip show httpx
          echo "----------------------------"
          
      # Langkah 4: Jalankan script bot Python
      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python muse_bot.py
