name: Run Telegram Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Langkah Paling Penting: Hapus semua cache yang mungkin ada
      - name: Force clean pip cache
        run: |
          echo "Clearing pip cache..."
          rm -rf ~/.cache/pip

      - name: Install dependencies from scratch
        run: |
          python -m pip install --upgrade pip
          # Paksa install ulang tanpa cache
          pip install --no-cache-dir -r requirements.txt

      # ----------------------------------------------------
      # BAGIAN DIAGNOSTIK PALING PENTING
      # ----------------------------------------------------
      - name: Verify Environment and Code
        run: |
          echo "--- Verifying requirements.txt content ---"
          cat requirements.txt
          echo "------------------------------------------"
          echo ""
          echo "--- Verifying installed httpx version and location ---"
          pip show httpx
          echo "------------------------------------------------------"
          echo ""
          echo "--- Verifying Python script content (first 50 lines) ---"
          head -n 50 muse_bot.py
          echo "--------------------------------------------------------"
      # ----------------------------------------------------

      - name: Run the bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python muse_bot.py
